### ISSUE TITLE
Lightbox of Content Element Type Image contorted the images

### ISSUE THREAD

**Issue by ProWebs** [t3solution/t3sbootstrap#241] opened 2022-08-12 14:09 UTC
Since we updated your extension to 4.5.4 on typo3 9.5.31 the images in your lightbox are displayed contorted.
Is this a known issue and was is solved in the next updates? Because 4.5.4 is the last avaiable version for typo 9.5.x

https://www.digitale-fotografien.com/privatkunden/hochzeitsfotografie/fotogalerie-hochzeit/fotos-standesamt

Many thanks.

**Comment by t3solution** [comment] 2022-08-14 07:34
This behavior is not known to me! 
Have you already selected a different lightbox?

**Comment by ProWebs** [comment] 2022-08-15 12:15
I can't access the "General Settings" on backend in this version.
Please see attached Video.

Uploading Backend.mp4…

**Comment by t3solution** [comment] 2022-08-16 08:35
You can replace the content of the file https://github.com/t3solution/t3sbootstrap/blob/master/Resources/Private/Backend/Partials/Config/Accordion.html with https://github.com/t3solution/t3sbootstrap/blob/4.4.5/Resources/Private/Backend/Partials/Version9/Accordion.html

**Comment by ProWebs** [comment] 2022-09-06 18:19
I replaced the content but now there is no General Settings ...

![grafik](https://user-images.githubusercontent.com/16188629/188709730-1dfbf8e5-adfe-439c-951b-05a4304f2fe6.png)

**Comment by ProWebs** [comment] 2022-09-06 18:22
If you look at the content of your proviced file there is also no Genaral Settings in you code:
https://github.com/t3solution/t3sbootstrap/blob/4.4.5/Resources/Private/Backend/Partials/Version9/Accordion.html

**Comment by t3solution** [comment] 2022-09-08 07:40
The problem is fixed with an update!
Or you exchange the BE templates with a more recent version!

**Comment by ProWebs** [comment] 2022-09-08 07:52
This is the last update you released for typo3 9.x so the last avaible version is complety useless with this bugs ...
A update to a newer version of your extension is only possible after updating to typo3 10.x which is not planed in the next days / weeks.

**Comment by t3solution** [comment] 2022-09-08 08:07
... then copy the entire ext/t3sbootstrap/Resources/Private/Backend/ directory from the next version in your installation!

**Comment by t3solution** [comment] 2022-09-08 18:32
Here is the solution for you:
In typo3conf/ext/t3sbootstrap/Resources/Private/Backend/Partials/Version9/Accordion.html
in line 6
change href="#collapseMeta"
to href="#collapseGeneral"

**Comment by ProWebs** [comment] 2022-10-01 23:07
Thanks. This solved the issue with General Settings.

But on this accordion is no selection for Lightboxes. Where is it possible to select a lightbox or look which one is activ by default?

"T3SB Config" on subpages
Use configuration from rootline (slide) if enabled or from rootpage if disabled.
If your installation only needs one configuration, this should be disabled!

(formerly known as a constant: bootstrap.config.rootline)

**Closed** 2023-04-05 08:41 UTC
